spring:
  application:
    name: EBAY_SHOPPING_ONLINE
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/testing_online
    username: root
    password: 123456
  jpa:
    hibernate.ddl-auto: none
    generate-ddl: true
    show-sql: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 10MB